#!/bin/bash
# Use this command to copy Arc to your Linux/MacOS Path: sudo cp arc /usr/bin/arc && sudo chmod a+rx arc 

# Enviromental Variables 
ASET="--no-overwrites --console-title --quiet --no-overwrites --embed-thumbnail --geo-bypass --add-metadata -f 37/22/18/best -x --audio-format "mp3" -o '%(title)s.%(ext)s' " #ASET sets audio option flags
VSET="--no-overwrites --console-title --quiet --no-overwrites --embed-thumbnail --geo-bypass --add-metadata -f 'bestvideo,bestaudio --recode-video "mp4" -o '%(title)s.%(ext)s' " #VSET sets video option flags 
BSET="--batch-file" # BSET sets Batch Settings for Batch Downloading 

while getopts v:a:h:b: flag
do
    case "${flag}" in
        v|video) youtube-dl $VSET ${OPTARG}
           echo [ARC] Operation has ended
           ;;
        a|audio) youtube-dl $ASET ${OPTARG} 
           echo [ARC] Operation has ended
           ;;
        b|batchmedia) ${OPTARG} #Args here is the file path for batch download
           read -p 'Audio or Video?(a/v): ' INPUT
           if [[ $INPUT == 'a' ]]
            then 
            youtube-dl $ASET $BSET ${OPTARG} 
           elif [[ $INPUT == 'v' ]]
            then 
            youtube-dl $VSET $BSET ${OPTARG} 
           else 
            echo Please type A for Audio or V for Video 
           fi 
           ;;
        c|createmediafile) $OPTARG
          read -p "What is the name of the file you want to create? : " FNAME 
          touch FNAME
          echo File created!
    esac
done 




